### ISSUE TITLE
log troubleshooting information when P6SpyDriver can not find the passthrough driver

### ISSUE THREAD

**Issue by quintonm** [p6spy/p6spy#171]
The log messages below came from the travis build log.  As you can see, it failed to find the H2 JDBC driver.  It would be helpful to have the contents of the classpath as well as the registered drivers in the log.

'''
[INFO] [talledLocalContainer] Caused by: liquibase.exception.DatabaseException: org.apache.tomcat.dbcp.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Unable to find a driver that accepts jdbc:h2:mem:p6spy)
[INFO] [talledLocalContainer] 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:293)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1541)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1479)
[INFO] [talledLocalContainer] 	... 36 more
[INFO] [talledLocalContainer] Caused by: org.apache.tomcat.dbcp.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Unable to find a driver that accepts jdbc:h2:mem:p6spy)
[INFO] [talledLocalContainer] 	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
[INFO] [talledLocalContainer] 	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSourcasicDataSource.java:1388)
[INFO] [talledLocalContainer] 	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
[INFO] [talledLocalContainer] 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:288)
[INFO] [talledLocalContainer] 	... 38 more
[INFO] [talledLocalContainer] Caused by: java.sql.SQLException: Unable to find a driver that accepts jdbc:h2:mem:p6spy
[INFO] [talledLocalContainer] 	at com.p6spy.engine.spy.P6SpyDriver.findPassthru(P6SpyDriver.java:119)
[INFO] [talledLocalContainer] 	at com.p6spy.engine.spy.P6SpyDriver.connect(P6SpyDriver.java:94)
[INFO] [talledLocalContainer] 	at org.apache.tomcat.dbcp.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
[INFO] [talledLocalContainer] 	at org.apache.tomcat.dbcp.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
[INFO] [talledLocalContainer] 	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
[INFO] [talledLocalContainer] 	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
[INFO] [talledLocalContainer] 	... 41 more
'''

**Comment by quintonm** [comment]
Closing issue since there is no reliable way that I can find to log the classpath.
