### ISSUE TITLE
P6OutagePreparedStatementSetParameterValueDelegate fails with java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by oysteinhagenpettersen** [p6spy/p6spy#275]
P6OutagePreparedStatementSetParameterValueDelegate fails with java.lang.ArrayIndexOutOfBoundsException: 1 when invoking set methods on the PreparedStatement.

Can be reproduced by invoking the P6TestPreparedStatement.testCallingSetMethodsOnStatementInterface with the P6Test_outage.properties.

Stacktrace:
 
    09:10:28,179 INFO  [com.p6spy.engine.test.P6TestFramework.<init>] P6Spy will be configured using P6Test_outage.properties
    09:10:28,254 INFO  [com.p6spy.engine.test.BaseTestCase.starting] 
    *****************************************************************************************

    Executing test testCallingSetMethodsOnStatementInterface[0: H2](com.p6spy.engine.spy.P6TestPreparedStatement)

    *****************************************************************************************
    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/C:/Users/et1205/.m2/repository/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/C:/Users/et1205/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.0-rc1/log4j-slf4j-impl-2.0-rc1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/C:/Users/et1205/.m2/repository/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
    09:10:28,573 INFO  [com.p6spy.engine.spy.P6TestUtil.setupTestData] Setting up database for testing
    1421309430341|0|statement|connection 0|drop table prepstmt_test|
    1421309430341|0|statement|connection 0|drop table prepstmt_test2|
    1421309430341|0|statement|connection 0|drop table prepstmt_test3|
    1421309430341|0|statement|connection 0|create table prepstmt_test (col1 varchar(255), col2 integer)|
    1421309430342|0|statement|connection 0|create table prepstmt_test2 (col1 varchar(255), col2 integer)|
    1421309430342|0|statement|connection 0|create table prepstmt_test3  (col1 timestamp)|
    1421309430408|0|statement|connection 0|drop table prepstmt_test|
    1421309430408|0|statement|connection 0|drop table prepstmt_test2|
    1421309430408|0|statement|connection 0|drop table prepstmt_test3|
    09:10:30,409 ERROR [com.p6spy.engine.test.BaseTestCase.failed] Failed test testCallingSetMethodsOnStatementInterface[0: H2](com.p6spy.engine.spy.P6TestPreparedStatement)
    java.lang.ArrayIndexOutOfBoundsException: 1
        at com.p6spy.engine.outage.P6OutagePreparedStatementSetParameterValueDelegate.invoke(P6OutagePreparedStatementSetParameterValueDelegate.java:42)
        at com.p6spy.engine.proxy.GenericInvocationHandler.invoke(GenericInvocationHandler.java:116)
        at org.p6spy.$java.sql.PreparedStatement$$EnhancerByCGLIB$$99c83682.setMaxRows(<generated>)
        at com.p6spy.engine.spy.P6TestPreparedStatement.testCallingSetMethodsOnStatementInterface(P6TestPreparedStatement.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.junit.runners.Suite.runChild(Suite.java:127)
        at org.junit.runners.Suite.runChild(Suite.java:26)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
        at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
    09:10:30,411 INFO  [com.p6spy.engine.test.BaseTestCase.finished] Completed test testCallingSetMethodsOnStatementInterface[0: H2](com.p6spy.engine.spy.P6TestPreparedStatement)

**Comment by quintonm** [comment]
Thanks for the bug report!  This will be fixed in 2.1.3.
