### ISSUE TITLE
On weblogic 12 and oracle jdbc, NoSuchMethodException

### ISSUE THREAD

**Issue by esteveblanch** [p6spy/p6spy#281]
When I try to configure weblogic 12C with P6spy, using oracle jdbc driver, program raises a NoSuchMethodException.

This is the complet stack:

```
java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:270)
    at com.p6spy.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:386)
    at com.p6spy.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219)
    at com.p6spy.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
    at com.p6spy.cglib.proxy.Enhancer.create(Enhancer.java:285)
    at com.p6spy.engine.proxy.ProxyFactory.createProxy(ProxyFactory.java:58)
    at com.p6spy.engine.logging.P6LogConnectionPrepareStatementDelegate.invoke(P6LogConnectionPrepareStatementDelegate.java:42)
    at com.p6spy.engine.proxy.GenericInvocationHandler.invoke(GenericInvocationHandler.java:116)
    at org.p6spy.oracle.jdbc.internal.OracleConnection$$EnhancerByCGLIB$$b14ea58c.prepareStatement(<generated>)
    at weblogic.jdbc.common.internal.ConnectionEnv.makeStatement(ConnectionEnv.java:1839)
    at weblogic.jdbc.common.internal.ConnectionEnv.getCachedStatement(ConnectionEnv.java:1549)
    at weblogic.jdbc.common.internal.ConnectionEnv.getCachedStatement(ConnectionEnv.java:1460)
    at weblogic.jdbc.common.internal.ConnectionEnv.getCachedStatement(ConnectionEnv.java:1453)
    at weblogic.jdbc.wrapper.Connection.prepareStatement(Connection.java:601)
    at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:233)
    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:531)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:587)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:612)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:644)
    at org.springframework.jdbc.object.SqlQuery.execute(SqlQuery.java:112)
    at org.springframework.jdbc.object.SqlQuery.execute(SqlQuery.java:199)
    at org.springframework.jdbc.object.SqlQuery.execute(SqlQuery.java:207)
    at xx.services.security.acegi.providers.dao.AuthoritiesJdbcImplDAO.getAuthoritiesIgnoreCase(AuthoritiesJdbcImplDAO.java:98)
    at xx.services.security.GICARUserDetailsServiceImpl.loadUserByUsername(GICARUserDetailsServiceImpl.java:107)
    at org.acegisecurity.providers.siteminder.SiteminderAuthenticationProvider.retrieveUser(SiteminderAuthenticationProvider.java:117)
    at org.acegisecurity.providers.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:167)
    at xx.services.security.acegi.providers.SequentialProviderManager.doAuthentication(SequentialProviderManager.java:89)
    at net.sf.acegisecurity.AbstractAuthenticationManager.authenticate(AbstractAuthenticationManager.java:49)
    at xx.services.security.SiteminderSessionAuthenticationProcessingFilter.attemptAuthentication(SiteminderSessionAuthenticationProcessingFilter.java:83)
    at xx.services.security.ProxyAuthenticationProcessingFilter.attemptAuthentication(ProxyAuthenticationProcessingFilter.java:128)
    at net.sf.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:306)
    at net.sf.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:303)
    at net.sf.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:220)
    at net.sf.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:303)
    at net.sf.acegisecurity.util.FilterChainProxy.doFilter(FilterChainProxy.java:173)
    at net.sf.acegisecurity.util.FilterToBeanProxy.doFilter(FilterToBeanProxy.java:120)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
    at xx.services.web.filter.HttpRequestWrapperFilter.doFilter(HttpRequestWrapperFilter.java:151)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
    at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3367)
    at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3333)
    at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
    at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
    at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
    at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2220)
    at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2146)
    at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2124)
    at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1564)
    at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:254)
    at weblogic.work.ExecuteThread.execute(ExecuteThread.java:295)
    at weblogic.work.ExecuteThread.run(ExecuteThread.java:254)
Caused By: java.lang.NoSuchMethodException: oracle.jdbc.internal.OracleStatement.getChecksum()
    at java.lang.Class.getDeclaredMethod(Class.java:2004)
    at com.p6spy.engine.proxy.P6Proxy$$EnhancerByCGLIB$$a1cbfc5.CGLIB$STATICHOOK6(<generated>)
    at com.p6spy.engine.proxy.P6Proxy$$EnhancerByCGLIB$$a1cbfc5.<clinit>(<generated>)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:270)
    at com.p6spy.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:386)
    at com.p6spy.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219)
    at com.p6spy.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
    at com.p6spy.cglib.proxy.Enhancer.create(Enhancer.java:285)
    at com.p6spy.engine.proxy.ProxyFactory.createProxy(ProxyFactory.java:58)
    at com.p6spy.engine.logging.P6LogConnectionPrepareStatementDelegate.invoke(P6LogConnectionPrepareStatementDelegate.java:42)
    at com.p6spy.engine.proxy.GenericInvocationHandler.invoke(GenericInvocationHandler.java:116)
    at org.p6spy.oracle.jdbc.internal.OracleConnection$$EnhancerByCGLIB$$b14ea58c.prepareStatement(<generated>)
    at weblogic.jdbc.common.internal.ConnectionEnv.makeStatement(ConnectionEnv.java:1839)
    at weblogic.jdbc.common.internal.ConnectionEnv.getCachedStatement(ConnectionEnv.java:1549)
    at weblogic.jdbc.common.internal.ConnectionEnv.getCachedStatement(ConnectionEnv.java:1460)
    at weblogic.jdbc.common.internal.ConnectionEnv.getCachedStatement(ConnectionEnv.java:1453)
    at weblogic.jdbc.wrapper.Connection.prepareStatement(Connection.java:601)
    at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:233)
    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:531)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:587)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:612)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:644)
    at org.springframework.jdbc.object.SqlQuery.execute(SqlQuery.java:112)
    at org.springframework.jdbc.object.SqlQuery.execute(SqlQuery.java:199)
    at org.springframework.jdbc.object.SqlQuery.execute(SqlQuery.java:207)
    at xx.services.security.acegi.providers.dao.AuthoritiesJdbcImplDAO.getAuthoritiesIgnoreCase(AuthoritiesJdbcImplDAO.java:98)
    at xx.services.security.GICARUserDetailsServiceImpl.loadUserByUsername(GICARUserDetailsServiceImpl.java:107)
    at org.acegisecurity.providers.siteminder.SiteminderAuthenticationProvider.retrieveUser(SiteminderAuthenticationProvider.java:117)
    at org.acegisecurity.providers.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:167)
    at xx.services.security.acegi.providers.SequentialProviderManager.doAuthentication(SequentialProviderManager.java:89)
    at net.sf.acegisecurity.AbstractAuthenticationManager.authenticate(AbstractAuthenticationManager.java:49)
    at xx.services.security.SiteminderSessionAuthenticationProcessingFilter.attemptAuthentication(SiteminderSessionAuthenticationProcessingFilter.java:83)
    at xx.services.security.ProxyAuthenticationProcessingFilter.attemptAuthentication(ProxyAuthenticationProcessingFilter.java:128)
    at net.sf.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:306)
    at net.sf.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:303)
    at net.sf.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:220)
    at net.sf.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:303)
    at net.sf.acegisecurity.util.FilterChainProxy.doFilter(FilterChainProxy.java:173)
    at net.sf.acegisecurity.util.FilterToBeanProxy.doFilter(FilterToBeanProxy.java:120)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
    at xx.services.web.filter.HttpRequestWrapperFilter.doFilter(HttpRequestWrapperFilter.java:151)
    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
    at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3367)
    at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3333)
    at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
    at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
    at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
    at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2220)
    at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2146)
    at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2124)
    at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1564)
    at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:254)
    at weblogic.work.ExecuteThread.execute(ExecuteThread.java:295)
    at weblogic.work.ExecuteThread.run(ExecuteThread.java:254)
```

**Comment by quintonm** [comment]
What version of P6Spy and the Oracle JDBC driver are you using?

**Comment by typekpb** [comment]
closing due to lack of feedback
