### ISSUE TITLE
Exception in P6LogResultSetDelegate when query has no parameters

### ISSUE THREAD

**Issue by jlamoree** [p6spy/p6spy#334]
When using p6spy-2.3.1.jar from jFrog Bintray, I see an issue with queries that do not have any bound parameters. When reverting to p6spy-2.1.4.jar, the problem does not present itself. Perhaps it's related to the changes in cglib? Here is the stack trace when I get the exception:
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.p6spy.engine.logging.P6LogResultSetDelegate.invoke(P6LogResultSetDelegate.java:45)
	at com.p6spy.engine.proxy.GenericInvocationHandler.invoke(GenericInvocationHandler.java:116)
	at com.p6spy.engine.proxy.P6Proxy$$EnhancerByCGLIB$$96ffa73c.getResultSet(<generated>)
	at coldfusion.server.j2ee.sql.JRunStatement.getResultSet(JRunStatement.java:283)
	at coldfusion.sql.Executive.getRowSet(Executive.java:609)
	at coldfusion.sql.Executive.executeQuery(Executive.java:1470)
	at coldfusion.sql.Executive.executeQuery(Executive.java:1201)
	at coldfusion.sql.Executive.executeQuery(Executive.java:1131)
	at coldfusion.sql.SqlImpl.execute(SqlImpl.java:406)
	at coldfusion.tagext.sql.QueryTag.executeQuery(QueryTag.java:1059)
	at coldfusion.tagext.sql.QueryTag.doEndTag(QueryTag.java:688)
...
```

I've been able to reproduce the problem with a simple query like this:
```
SELECT * FROM sys.tables
```
However, this query works just fine (when the application server performs its query statement processing and binds the VARCHAR parameter as "foo"):
```
SELECT * FROM sys.tables WHERE name = 'foo'
```

This is the content of my spy.properties file:
```
driverlist=net.sourceforge.jtds.jdbc.Driver,com.microsoft.sqlserver.jdbc.SQLServerDriver
reloadproperties=true
reloadpropertiesinterval=30
append=true
appender=com.p6spy.engine.spy.appender.FileLogger
logfile=/home/tomcat/servers/myapp/logs/spy.log
```

Switching from the Microsoft JDBC (v4.0.2206.100) driver to the jTDS JDBC (1.3.1) driver shows the same problem with a similar stack trace:
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.p6spy.engine.logging.P6LogResultSetDelegate.invoke(P6LogResultSetDelegate.java:45)
	at com.p6spy.engine.proxy.GenericInvocationHandler.invoke(GenericInvocationHandler.java:116)
	at $java.sql.Statement$$EnhancerByCGLIB$$207673e7.getResultSet(<generated>)
	at coldfusion.server.j2ee.sql.JRunStatement.getResultSet(JRunStatement.java:283)
	at coldfusion.sql.Executive.getRowSet(Executive.java:609)
	at coldfusion.sql.Executive.executeQuery(Executive.java:1470)
	at coldfusion.sql.Executive.executeQuery(Executive.java:1201)
	at coldfusion.sql.Executive.executeQuery(Executive.java:1131)
	at coldfusion.sql.SqlImpl.execute(SqlImpl.java:406)
	at coldfusion.tagext.sql.QueryTag.executeQuery(QueryTag.java:1059)
	at coldfusion.tagext.sql.QueryTag.doEndTag(QueryTag.java:688)
...
```

**Comment by felixbarny** [comment]
Which kind of statement causes this error? Statement, PreparedStatement or CallableStatement? Could you paste the code which creates and executes the statement? It seems you're using an abstraction provided by coldfusion. That might make debugging a bit trickier..

**Comment by jlamoree** [comment]
When I revert back to p6spy-2.1.4.jar, and use the example query above, the output in the log file is this:
```
spy myapp 1469147984241|26|statement|connection 0|SELECT * FROM sys.tables WHERE name = ?|SELECT * FROM sys.tables WHERE name = 'foo' 
```
For what it's worth, this is the CFML source that caused the logged JDBC statement:
```
<cfquery name="foo" datasource="myapp">
SELECT * FROM sys.tables WHERE name = <cfqueryparam cfsqltype="CF_SQL_VARCHAR" value="foo"/>
</cfquery>
```
I happen to be using Adobe® ColdFusion® 10 at the moment. I could try using one of the popular open source CFML engines if that would be helpful.

**Comment by felixbarny** [comment]
I'm on vacation the next week so I unfortunately can't diagnose the problem but I'm sure another maintainer will chime in.

**Comment by typekpb** [comment]
Sry guys, I'm on vacation current as well as next week so won't help here

**Comment by felixbarny** [comment]
This error should however be fixed in master as p6spy 3.0 will not rely on cglib anymore. It would be great if you could try out the current master!

The only way I can think of that this errror can occur is that a prepared statement is initialized with `Connection#prepareStatement(null)`. Porobably a simple bounds check [here](https://github.com/p6spy/p6spy/blob/2.X/src/main/java/com/p6spy/engine/logging/P6LogResultSetDelegate.java#L45) would fix that problem. If you could verify that, a pull request would be really hepful as most of the maintainers are on vacation atm.

**Comment by jlamoree** [comment]
I will give the master branch a try. I've had limited success in building Maven projects in the past, but I will do my best.

**Comment by typekpb** [comment]
Hey! No need for rebuild manually. We've recently released 3.0.0 alpha 1
version. See:
https://github.com/p6spy/p6spy/releases/tag/p6spy-3.0.0-alpha-1

**Comment by typekpb** [comment]
Recently = a day ago :)

**Comment by jlamoree** [comment]
I dropped p6spy-3.0.0-alpha-1.jar into my application without making any other changes at all. It works just fine. The issue with a query having no bound parameters is resolved in the latest and greatest.

Thank you.

**Comment by felixbarny** [comment]
@contributors do you think we should bother fixing this in 2.x?

**Comment by typekpb** [comment]
I wouldn't, as we anyway want to encourage people to use the latest and
greatest one, I guess.

On Jul 31, 2016 13:29, "Felix" <notifications@github.com> wrote:

@contributors <https://github.com/contributors> do you think we should
bother fixing this in 2.x?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/p6spy/p6spy/issues/334#issuecomment-236424979>, or mute
the thread

**Comment by felixbarny** [comment]
Ok, then I'm closing this as a known issue in 2.3.
