### ISSUE TITLE
Wildfly 10: java.sql.SQLException: Unable to find a driver that accepts jdbc:oracle:thin:@localhost:1521:XE

### ISSUE THREAD

**Issue by siom79** [p6spy/p6spy#388]
After having installed the p6spy driver as described [here](http://p6spy.readthedocs.io/en/latest/install.html#jboss-wildfly) the following exception appeared in the server.log file when starting the Wildfly 10.0.0.Final server:
```
java.sql.SQLException: Unable to find a driver that accepts jdbc:oracle:thin:@localhost:1521:XE
	at com.p6spy.engine.spy.P6SpyDriver.findPassthru(P6SpyDriver.java:122)
	at com.p6spy.engine.spy.P6SpyDriver.connect(P6SpyDriver.java:91)
 	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:319)
[...]
```
Debugging the p6spy driver showed that the Oracle driver defined in standalone.xml is not available via `DriverManager.getDrivers()`. This is due to the fact that the classloader for the p6spy module does not "see" the Oracle driver. Hence it must be added as dependency to the `module.xml` file:
```
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.1" name="com.p6spy">
	<resources>
		<resource-root path="p6spy-3.0.0.jar"/>
	</resources>
	<dependencies>
		<module name="javax.api"/>
		<module name="javax.transaction.api"/>
		<module name="com.oracle.ojdbc6"/>
	</dependencies>
</module>
```
The Oracle JDBC driver is also installed as a module (in `$JBOSS_HOME/modules/system/layers/base/com/oracle/ojdbc6/main`):
```
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.1" name="com.oracle.ojdbc6">
	<resources>
		<resource-root path="ojdbc6-11.2.0.1.0.jar"/>
	</resources>
	<dependencies>
		<module name="javax.api"/>
		<module name="javax.transaction.api"/>
	</dependencies>
</module>
```
In `standalone.xml` I have configured the datasource and drivers as follows:
```
                <datasource jta="true" jndi-name="java:jboss/MY_DS" pool-name="MY_DS" enabled="true" use-java-context="true">
                    <connection-url>jdbc:p6spy:oracle:thin:@localhost:1521:XE</connection-url>
                    <driver>p6spy</driver>
                    <pool>
                        <min-pool-size>5</min-pool-size>
                        <max-pool-size>75</max-pool-size>
                        <prefill>true</prefill>
                    </pool>
                    <security>
                        <user-name>xxx</user-name>
                        <password>xxx</password>
                    </security>
                    <timeout>
                        <idle-timeout-minutes>60000</idle-timeout-minutes>
                        <allocation-retry>5</allocation-retry>
                    </timeout>
                </datasource>
                <drivers>
                    <driver name="oracle" module="com.oracle.ojdbc6">
                        <xa-datasource-class>oracle.jdbc.OracleDriver</xa-datasource-class>
                    </driver>
                    <driver name="p6spy" module="com.p6spy">
                        <xa-datasource-class>com.p6spy.engine.spy.P6SpyDriver</xa-datasource-class>
                    </driver>
                </drivers>
```
Please note that both drivers have to added (oracle and p6spy).

Can you update the documentation accordingly? Thanks in advance.

**Comment by typekpb** [comment]
Excelent! Any chance for creating the pull request?

**Comment by typekpb** [comment]
#389 merged => closing
