### ISSUE TITLE
com.p6spy.engine.logging.P6LogFactory cannot be cast to com.p6spy.engine.spy.P6Factory

### ISSUE THREAD

**Issue by anandvarkeyphilips** [p6spy/p6spy#414]
Hi Team,
I facing this issue in 3.4.0 version. Not sure if it is a configuration problem. I have put jar and spy.properties in Apache/lib. Configured data source in context.xml.

**Contex.xml**
`<Resource driverClassName="com.p6spy.engine.spy.P6SpyDriver" maxActive="100" maxIdle="2"   maxWait="6000" name="NAME"  password="password" type="javax.sql.DataSource"   url="jdbc:p6spy:oracle:thin:@11.111.11.111:1525:schema" username="username" validationQuery="select * from dual" />`

**Stacktrace**

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory' defined in ServletContext resource [/WEB-INF/spring.xml]: Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1486)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:461)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:323)
	... 51 more
Caused by: java.lang.ExceptionInInitializerError
	at com.p6spy.engine.spy.P6SpyDriver.findPassthru(P6SpyDriver.java:117)
	at com.p6spy.engine.spy.P6SpyDriver.connect(P6SpyDriver.java:88)
	at org.apache.tomcat.dbcp.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.tomcat.dbcp.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.tomcat.dbcp.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at org.springframework.orm.hibernate3.LocalDataSourceConnectionProvider.getConnection(LocalDataSourceConnectionProvider.java:83)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:113)
	at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2836)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2832)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1843)
	at org.springframework.orm.hibernate3.LocalSessionFactoryBean.newSessionFactory(LocalSessionFactoryBean.java:863)
	at org.springframework.orm.hibernate3.LocalSessionFactoryBean.buildSessionFactory(LocalSessionFactoryBean.java:782)
	at org.springframework.orm.hibernate3.AbstractSessionFactoryBean.afterPropertiesSet(AbstractSessionFactoryBean.java:188)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1483)
	... 58 more
  Caused by: java.lang.ClassCastException: com.p6spy.engine.logging.P6LogFactory cannot be cast to com.p6spy.engine.spy.P6Factory
	at com.p6spy.engine.spy.P6ModuleManager.<init>(P6ModuleManager.java:128)
	at com.p6spy.engine.spy.P6ModuleManager.initMe(P6ModuleManager.java:66)
	at com.p6spy.engine.spy.P6ModuleManager.<clinit>(P6ModuleManager.java:59)
	... 76 more
```

**Comment by typekpb** [comment]
@anandvarkeyphilips sorry, I guess I haven't seen this issue before.

Anyway, code says:
`public class P6LogFactory implements P6Factory`

so to me it seems like a classloading issue, (probably you have p6spy jar present multiple times on your classpath, possibly in different versions).

Please make sure that you have the library present in your application/application server only once.

**Comment by typekpb** [comment]
well, found similar one repored in the past: #189, maybe @quintonm would remember. Anyway, I guess I don't fully understand the way we could solve it.
@quintonm @felixbarny ideas?

**Comment by anandvarkeyphilips** [comment]
Hi.. Looks like I had 2 jars and thats the issue!
