### ISSUE TITLE
NullPointer at start. p6spy-3.8.3 

### ISSUE THREAD

**Issue by dmitryallen** [p6spy/p6spy#478]
We are getting nullpointer exception on AWS EC2, configuration is working well under Windows. 
Exception: 
Caused by: java.lang.NullPointerException
        at com.p6spy.engine.spy.appender.StdoutLogger.logText(StdoutLogger.java:37)
        at com.p6spy.engine.spy.appender.FormattedLogger.logSQL(FormattedLogger.java:35)
        at com.p6spy.engine.common.P6LogQuery.doLog(P6LogQuery.java:121)
        at com.p6spy.engine.common.P6LogQuery.doLogElapsed(P6LogQuery.java:91)
        at com.p6spy.engine.common.P6LogQuery.logElapsed(P6LogQuery.java:203)
        at com.p6spy.engine.logging.LoggingEventListener.logElapsed(LoggingEventListener.java:107)
        at com.p6spy.engine.logging.LoggingEventListener.onAfterCommit(LoggingEventListener.java:54)
        at com.p6spy.engine.event.CompoundJdbcEventListener.onAfterCommit(CompoundJdbcEventListener.java:285)
        at com.p6spy.engine.wrapper.ConnectionWrapper.commit(ConnectionWrapper.java:172)
        at com.mchange.v2.c3p0.impl.NewProxyConnection.commit(NewProxyConnection.java:981)
        at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:50)
        at org.hibernate.tool.schema.internal.exec.ImprovedExtractionContextImpl.getJdbcConnection(ImprovedExtractionContextImpl.java:60)
        at org.hibernate.tool.schema.internal.exec.ImprovedExtractionContextImpl.getJdbcDatabaseMetaData(ImprovedExtractionContextImpl.java:67)
        at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.getTables(InformationExtractorJdbcDatabaseMetaDataImpl.java:329)
        at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.getTablesInformation(DatabaseInformationImpl.java:120)
        at org.hibernate.tool.schema.internal.GroupedSchemaMigratorImpl.performTablesMigration(GroupedSchemaMigratorImpl.java:65)
        at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.performMigration(AbstractSchemaMigrator.java:207)
        at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:114)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:183)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:72)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:310)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:467)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:708)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:724)
        at org.springframework.orm.hibernate5.LocalSessionFactoryBean.buildSessionFactory(LocalSessionFactoryBean.java:416)
        at org.springframework.orm.hibernate5.LocalSessionFactoryBean.afterPropertiesSet(LocalSessionFactoryBean.java:401)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
        ... 21 more

**Comment by typekpb** [comment]
Is it specific to 3.8.3? Can you reproduce with 3.8.2 as well?

**Comment by typekpb** [comment]
One more on the topic: Can you reproduce ommiting the p6spy? As `NullPointer` seems to be triggered elsewhere (not in the p6spy code).

**Comment by dmitryallen** [comment]
Unfortunately I cannot reproduce it. Under windows application it's running under Jetty and in AWS under Tomcat. Perhaps problem is connected to log system and it just cannot take a logger instance. It would be nice to have some error message with reason to understand what's wrong.

**Comment by gavlyukovskiy** [comment]
@dmitryallen are you using `appender=com.p6spy.engine.spy.appender.FileLogger`? If yes does application have permission to create log file specified in `logfile` (default `spy.log`)? 
I believe error is written into error stream, can you check?

**Comment by gavlyukovskiy** [comment]
@dmitryallen I changed writing error into `System.err` with rethrowing exception, if there is exception it should be more clear now.

**Comment by typekpb** [comment]
@dmitryallen another `NullPointerException` fix provided with 3.8.5 version (released just now, should be eventually synced to maven central repo). Please retest and report back if the exception is gone for your use-case.

**Comment by axioncontact** [comment]
Thanks, 
application has permission to write in the log folder, other logs are working well.
