### ISSUE TITLE
executeLargeUpdate not implemented

### ISSUE THREAD

**Issue by tlf30** [p6spy/p6spy#540]
Hello, 
I'm using pgjdbc-ng and hikari to connect to a postgresql 14 database. 
Without P6Spy my application works great, but when I implemented the `P6DataSource` wrapper around my pgjdbc-ng datasource before handing it to hikari, I receive the following error that executeLargeUpdate is not implemented.

```
java.lang.UnsupportedOperationException: executeLargeUpdate not implemented
	at java.sql/java.sql.PreparedStatement.executeLargeUpdate(PreparedStatement.java:1320)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeLargeUpdate(HikariProxyPreparedStatement.java)
        ... <stack trace censored>
```

I use two executeLargeUpdate on a prepared statement in two places due to selecting a massive number of rows. (yes, this takes a while) It would be great to get this implemented in P6Spy.

**Comment by tlf30** [comment]
I found another one, `setObject` is not implemented.
```
java.sql.SQLFeatureNotSupportedException: setObject not implemented
	at java.sql/java.sql.PreparedStatement.setObject(PreparedStatement.java:1293)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setObject(HikariProxyPreparedStatement.java)
```
